title: Jerrygoyal
email: 1gouravgg@gmail.com
description: Developer profile of Gourav Goyal.
twitter_username: Your Twitter username (do not include @ symbol).
github_username: jerrygoyal
plugins:
  - jekyll-redirect-from
# sass:
#   style: compressed