title: Gourav Goyal
email: 1gouravgg@gmail.com
description: Developer profile of Gourav Goyal.
twitter_username: GorvGoyl
github_username: GorvGoyl
livereload: true
url: "https://Gourav.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
# sass:
#   style: compressed

exclude:
  - functions/
  - help.md
  - firebase-debug.log
